x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 20m
      max-file: "3"

services:
  stunnel:
    build:
      context: ./stunnel
      dockerfile: Dockerfile.source
      args:
        - STUNNEL_VERSION=${STUNNEL_VERSION}
        - USER=stunnel
    image: stunnel:v${STUNNEL_VERSION}-local
    pull_policy: never
    user: stunnel
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      - LOCAL_PORT=${LOCAL_PORT:-1000}
      - CONNECT_ADDR=${CONNECT_ADDR}
      - PSK=${PSK}
    ports:
      - ${LOCAL_PORT:-1000}:${LOCAL_PORT:-1000}/tcp
    entrypoint:
      - docker-entrypoint.sh
      - stunnel
      - /stunnel/stunnel.conf
    labels:
        - traefik.enable=false
        - metrics.scrape=false
